# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organize',
            name='introduce',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organize',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
