# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='activity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='qq',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='schoolid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='wechat',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
