# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizeid', models.IntegerField()),
                ('organizedepartid', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('state', models.IntegerField()),
                ('auditsug', models.CharField(max_length=300, null=True)),
                ('identity', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'associateinfo',
            },
        ),
    ]
