# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('sex', models.IntegerField(null=True)),
                ('workid', models.CharField(max_length=20, null=True)),
                ('mobilephone', models.CharField(max_length=12, null=True)),
                ('wechat', models.CharField(max_length=20, null=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('universityid', models.IntegerField(null=True)),
                ('schoolid', models.IntegerField(null=True)),
                ('departmentid', models.IntegerField(null=True)),
                ('majorid', models.IntegerField(null=True)),
                ('classid', models.IntegerField(null=True)),
                ('interest', models.CharField(max_length=200, null=True)),
                ('state', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
    ]
